    name: Second Workflow
    on: 
        push:
        workflow_dispatch:
        

    jobs:
        hello-job:
            runs-on: ubuntu-latest 
            steps:
                - name: "welcome"
                  run: echo "welcome to the code"
        bye-job:
            runs-on: ubuntu-latest
            steps:
                - name: "bye"
                  run: echo "bye bye and please like my code"
            
